# Generated by Django 3.2 on 2021-10-05 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfolio_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='specificationcard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
