# Generated by Django 3.2 on 2021-09-24 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0001_initial'),
        ('users', '0001_initial'),
        ('tags', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=120)),
                ('deadline', models.DateTimeField()),
                ('memo', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='')),
                ('Portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfolio')),
                ('mentees', models.ManyToManyField(related_name='participated_mentoring', to='users.User')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opened_mentoring', to='users.user')),
                ('tags', models.ManyToManyField(to='tags.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=120)),
                ('content', models.TextField()),
                ('deadline', models.DateTimeField()),
                ('mentoring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentoring.mentoring')),
                ('passed_mentees', models.ManyToManyField(to='users.User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
