# Generated by Django 3.2 on 2021-10-02 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tags', '0001_initial'),
        ('mentoring', '0001_initial'),
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentoring',
            name='mentees',
            field=models.ManyToManyField(related_name='participated_mentoring', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mentoring',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opened_mentoring', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mentoring',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfolio'),
        ),
        migrations.AddField(
            model_name='mentoring',
            name='tags',
            field=models.ManyToManyField(to='tags.Tag'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='mentoring',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='mentoring.mentoring'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='passed_mentees',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
