# Generated by Django 3.2 on 2021-10-05 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentoring',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
