# Generated by Django 3.2 on 2021-09-26 06:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0002_rename_portfolio_mentoring_portfolio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentoring',
            old_name='deadline',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='mentoring',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='mentoring',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='mentoring.mentoring'),
        ),
    ]
